---
hero_image: images/banner.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Moonhack Scratch 2017
description: Simulate the difference between jumping on The Moon compared to jumping on Earth.
original_url: https://codeclubprojects.org/en-GB/scratch/moonhack-scratch
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Make Scratchy walk
  - 
    title: Create Jumping Blocks
  - 
    title: Scratchy Jumps
  - 
    title: 'Challenge: Adding a sound'
  - 
    title: 'Challenge: Mars Jump'
  - 
    title: 'Challenge: Custom stage'
